### ISSUE TITLE
Tables creation from Exchange AST

### ISSUE THREAD

**Issue by termoshtt** [ricosjp/ruststep#12]
Before creating tables automatically by espr as described in ARCHITECTURE.md, we must try to create them by hand to determine its specification.

TODO
--------
- [x] Create tables manually #15 
- [x] Convert Exchange AST to manually generated tables #22 
  - [x] Basic serde integration (for HEADER section) #18 
  - [x] Nested record support #21
  - [x] `PlaceHolder` for reference e.g. `A((1.0, #11))` #20
- [x] Documents for tables submodule #24
- ~~Generate tables definitions by espr~~
- ~~Add about serde in ARCHITECTURE.md~~
