### ISSUE TITLE
Enum-based supertype

### ISSUE THREAD

**Issue by termoshtt** [ricosjp/ruststep#83]
Objective
-----------
Represent EXPRESS's super/sub types as Rust's enum instead of trait object `Box<dyn *Any>`. This is mainly due to serde does not supports trait object.

- [x] Definition #82, #84
- [x] Codegen #80 
- [x] Serialize, Deserialize #70 
- [x] Update ARCHITECTURE.md #112 

Subtype-Supertype Graph
-----------------------------
Revival of #40. Since we have to gather all subtypes to define supertype enum, `SubSuperGraph` will be constructed after `Namespace` creation and before `Legalize`. Though the `ENTITY` in EXPRESS schema has `SUPERTYPE OF` declaration, it does not list up all subtypes correctly https://github.com/ricosjp/ruststep/pull/80#issuecomment-887019104

- [x] Create `SubSuperGraph` #86, use for `ABSTRACT SUPERTYPE` case
- [x] Use sub-super graph always #88

**Comment by termoshtt** [comment]
Done :tada:
